add wave -noupdate -divider {Em_Irobot_CPU: top-level ports}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/i_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/i_readdatavalid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/i_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/i_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/i_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/d_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/d_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/d_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/d_byteenable
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/d_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/d_write
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/d_writedata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/d_irq
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/d_readdatavalid
add wave -noupdate -divider {Em_Irobot_CPU: base pipeline}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/D_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/F_pcb_nxt
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/F_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/D_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/E_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/M_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/W_pcb
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Em_Irobot_CPU/F_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Em_Irobot_CPU/D_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Em_Irobot_CPU/E_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Em_Irobot_CPU/M_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Em_Irobot_CPU/A_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Em_Irobot_CPU/W_vinst
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/F_inst_ram_hit
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/F_iw_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/F_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/F_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/D_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/D_refetch
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/D_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/D_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/D_rdprs_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/D_rdprs_stall_done
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/E_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/M_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/W_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/W_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/W_dst_regnum
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/W_wr_data
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/D_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/E_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/M_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/F_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/D_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/E_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/M_pipe_flush
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/M_pipe_flush_baddr
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/norm_intr_req
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_status_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_status_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_estatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_estatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_bstatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_bstatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_ienable_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_ienable_reg_irq0
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_ienable_reg_irq1
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_ienable_reg_irq2
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_ipending_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_ipending_reg_irq0
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_ipending_reg_irq1
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_ipending_reg_irq2
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/A_cpuid_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Em_Irobot_CPU/E_valid_prior_to_hbreak

configure wave -justifyvalue right
configure wave -signalnamewidth 1
TreeUpdate [SetDefaultTree]
